# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SNIST_BOT_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SNIST_BOT_UI(object):
    def setupUi(self, SNIST_BOT_UI):
        SNIST_BOT_UI.setObjectName("SNIST_BOT_UI")
        SNIST_BOT_UI.resize(1908, 1009)
        self.centralwidget = QtWidgets.QWidget(SNIST_BOT_UI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-1230, -170, 3271, 1221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1300, 10, 691, 571))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Iron_Template_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, -120, 511, 401))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("initial.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1050, 860, 251, 101))
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(85, 255, 255);\n"
"font: 75 22pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1470, 600, 421, 381))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Hero_Template.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(690, 860, 221, 101))
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(600, 20, 761, 181))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Capture.PNG"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.text__brower_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text__brower_2.setGeometry(QtCore.QRect(20, 240, 261, 101))
        self.text__brower_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                           "border-radius:none;\n"
                                       "color:white;\n"
                                       "font-size:20px")
        self.text__brower_2.setObjectName("text__brower_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(580, 190, 791, 161))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("loading_1.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(320, 380, 261, 91))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                       "border-radius:none;\n"
                                       "color:white;\n"
                                       "font-size:20px")
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 510, 711, 521))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Ntuks.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 370, 681, 511))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Earth.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.text__brower_2.raise_()
        self.textBrowser.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        SNIST_BOT_UI.setCentralWidget(self.centralwidget)

        self.retranslateUi(SNIST_BOT_UI)
        QtCore.QMetaObject.connectSlotsByName(SNIST_BOT_UI)

    def retranslateUi(self, SNIST_BOT_UI):
        _translate = QtCore.QCoreApplication.translate
        SNIST_BOT_UI.setWindowTitle(_translate("SNIST_BOT_UI", "MainWindow"))
        self.pushButton_2.setText(_translate("SNIST_BOT_UI", "TERMINATE"))
        self.pushButton.setText(_translate("SNIST_BOT_UI", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SNIST_BOT_UI = QtWidgets.QMainWindow()
    ui = Ui_SNIST_BOT_UI()
    ui.setupUi(SNIST_BOT_UI)
    SNIST_BOT_UI.show()
    sys.exit(app.exec_())
